# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - '*'  

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  inputs:
    workingDirectory: "$(Build.Repository.LocalPath)/testcontainers/java-demo"
    gradleWrapperFile: "$(Build.Repository.LocalPath)/testcontainers/java-demo/gradlew"
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- task: NodeTool@0 
  inputs:
    versionSpec: '16.x' 
  displayName: 'Install Node.js version 16'

# - task: Npm@1
#   inputs:
#     command: 'install'
#     workingDir: "$(Build.Repository.LocalPath)/svelte/example1"
